apiVersion: v1
kind: Pod
metadata:
  name: busybox334
spec:
  containers:
    - name: busybox
      image: busybox:1.28.4
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  dnsPolicy: Default